# Numpy Assignment

In [3]:
import numpy as np

#### 1. min()

In [5]:
a = np.arange(0, 8,1).reshape(2,4)

In [29]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [11]:
a.min()

0

In [16]:
var = a[0][0]
for i in a:
    for j in i:
        if(j<var):
            var = j
            
print ("Min = ", var)

Min =  0


#### 2. max()

In [18]:
a.max()

7

In [20]:
var = a[0][0]
for i in a:
    for j in i:
        if(j>var):
            var = j
            
print ("Max = ", var)

Max =  7


#### 3. mean()

In [25]:
a.mean()

3.5

In [26]:
var = 0
for i in a:
    for j in i:
        var = var + j
mean = var/a.size
print("Sum = ", mean)

Sum =  3.5


#### 4. argmin()

In [125]:
a.argmin(axis = 0)

array([0, 0, 0])

In [126]:
b = np.array([[4, 0, 2],[8,9,-1]])
b.argmin()
b.argmin(axis = 0)

array([0, 0, 1])

In [58]:
index_list = []
for i in b:
    store = i[0]
    index = 0
    
    for j in i:
        if j < store:
            store = j
            min_index = index
        index +=1
    
    index_list.append(min_index)

print("Argmin along axis = 1 is ",index_list)
    

Argmin along axis = 1 is  [1, 2]


#### 5. argmax()

In [72]:
b.argmax(axis = 1)

array([0, 1])

In [61]:
index_list = []
max_index = 0
for i in b:
    store = i[0]
    index = 0
    
    for j in i:
        if j > store:
            store = j
            max_index = index
        index +=1
    
    index_list.append(max_index)

print("Argmax along axis = 1 is ",index_list)

Argmax along axis = 1 is  [0, 1]


#### 6. linalg.solve

In [129]:
c = np.array([[3,1],[1,2]]) 
d = np.array([[9],[8]])
np.linalg.solve(c,d)

array([[ 2.],
       [ 3.]])

#### 7. flatten

In [66]:
flatten_list = []
for i in b:
    for j in i:
        flatten_list.append(j)
print(flatten_list)
    

[4, 0, 2, 8, 9, -1]


#### 8. ravel

In [130]:
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [132]:
k = np.empty(a.size)

for i in range(a.size):
    k[i] = a.item(i)
k

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

#### 9. Dot product

In [158]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [159]:
result = np.array([[0,0],[0,0]])
for i in range(len(a)):
    for j in range(len(b[0])):
        for k in range(len(b)):
            result[i][j] += a[i][k] * b[k][j]

for r in result:
    print(r)
    

[19 22]
[43 50]


#### 10. Matrix multiplaction

In [138]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.multiply(a,b)

array([[ 5, 12],
       [21, 32]])

In [139]:
result = ([[0,0],[0,0]])
a_rows,a_cols = a.shape
for i in range(a_rows):
    for j in range(a_cols):
        result[i][j] = a[i][j]*b[i][j]
print("without using api")
for k in result:
    print(k)

without using api
[5, 12]
[21, 32]


#### 11. Reshape

In [140]:
a.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

#### 12. Identity

In [142]:
a = np.identity(3)
print(a)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [143]:
b = np.empty(a.size)
s = 0
a_rows, a_cols = a.shape
for i in range(a_rows):
    for j in range(a_cols):
        if i == j:
            b[s] = 1
            s += 1
        else:
            b[s] = 0
            s += 1
b.reshape(a_rows,a_cols)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### 13. sum()

In [144]:
a.sum()

3.0

In [145]:
var = 0
for i in a:
    for j in i:
        var = var + j
print("Sum = ", var)

Sum =  3.0


#### 14. Diag

In [150]:
a = np.arange(9).reshape(3,3)
print(a)
np.diag(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 4, 8])

In [151]:
s = 0
a_rows, a_cols = a.shape
b = np.empty((a_rows))
for i in range(a_rows):
    for j in range(a_cols):
        if i == j:
            b[s] = a[i,j]
            s += 1
print("without using inbuilt api diagonal array is",b)


without using inbuilt api diagonal array is [ 0.  4.  8.]


#### 15. tril

In [155]:
a = np.arange(9).reshape(3,3)
np.tril(a)

array([[0, 0, 0],
       [3, 4, 0],
       [6, 7, 8]])

In [156]:
b = np.empty(a.size)
s = 0
a_rows, a_cols = a.shape
for i in range(a_rows):
    for j in range(a_cols):
        if i < j:
            b[s] = 0
            s += 1
        else:
            b[s] = a[i,j]
            s += 1
b.reshape(a_rows, a_cols)

array([[ 0.,  0.,  0.],
       [ 3.,  4.,  0.],
       [ 6.,  7.,  8.]])